name: my-ci-pipeline

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v4

      - name: build docker image
        run: docker compose build --pull next-app

      - name: test in docker
        run: docker compose run --rm next-app npm test -- --ci --runInBand
